GET http://127.0.0.1:3000/

####
GET http://127.0.0.1:3000/action/get/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjBiZjlmNi04ZGY3LTQ3MDQtYjQxZi1kYTExYmE2ZmZmMjQiLCJpYXQiOjE3MzE5Mzg1Mzh9.OsHn8W0QLqpEaH09j5GsqHfSgnyaCav42-2io7bi_no

####
GET http://127.0.0.1:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjBiZjlmNi04ZGY3LTQ3MDQtYjQxZi1kYTExYmE2ZmZmMjQiLCJpYXQiOjE3MzE5MzY2ODMsImV4cCI6MTczMTk0MDI4M30.p7Y74p_u3B0jgodSBwiAKkfKHI7nb_LD_frQYzz5uos

####
POST http://127.0.0.1:3000/register
Content-Type:application/json

{
    "Email":"geraldoal@gmail.com",
    "Password":"lklssffdbs",
    "Username":"Antonio"
}

####
POST http://127.0.0.1:3000/action/post/transaction
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjBiZjlmNi04ZGY3LTQ3MDQtYjQxZi1kYTExYmE2ZmZmMjQiLCJpYXQiOjE3MzE5Mzg1Mzh9.OsHn8W0QLqpEaH09j5GsqHfSgnyaCav42-2io7bi_no

{
    "Value":2000,
    "Type":"Positivo"
}

####
PATCH http://127.0.0.1:3000/auth/login
Content-Type:application/json

{
    "Email":"geraldoal@gmail.com",
    "Password":"lklssffdbs"
}